[admin:TA-cisco-fmc]
match = /
members = TA-cisco-fmc_account, TA-cisco-fmc_cisco_fmc_health, TA-cisco-fmc_settings, ta_cisco_fmc_domain_handler

[admin_external:TA-cisco-fmc_account]
handlertype = python
python.version = python3
handlerfile = TA-cisco-fmc_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA-cisco-fmc_settings]
handlertype = python
python.version = python3
handlerfile = TA-cisco-fmc_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA-cisco-fmc_cisco_fmc_health]
handlertype = python
python.version = python3
handlerfile = TA-cisco-fmc_rh_cisco_fmc_health.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
[admin_external:ta_cisco_fmc_domain_handler]
handlertype = python
python.version = python3
handlerfile = fmc_domain_handler.py
handleractions = list
handlerpersistentmode = true