[expose:TA-cisco-fmc_account]
pattern = TA-cisco-fmc_account
methods = POST, GET

[expose:TA-cisco-fmc_account_specified]
pattern = TA-cisco-fmc_account/*
methods = POST, GET, DELETE

[expose:TA-cisco-fmc_settings]
pattern = TA-cisco-fmc_settings
methods = POST, GET

[expose:TA-cisco-fmc_settings_specified]
pattern = TA-cisco-fmc_settings/*
methods = POST, GET, DELETE

[expose:TA-cisco-fmc_cisco_fmc_health]
pattern = TA-cisco-fmc_cisco_fmc_health
methods = POST, GET

[expose:TA-cisco-fmc_cisco_fmc_health_specified]
pattern = TA-cisco-fmc_cisco_fmc_health/*
methods = POST, GET, DELETE
[expose:ta_cisco_fmc_domain_handler]
pattern = ta_cisco_fmc_domain_handler
methods = GET